#  .properties 계층구조 중복 발생
#  #yml, yaml을 통해 들여쓰기 계층구조 사용
#
#  port 번호 변경 (default 8080)
server:
  port: 8080
spring :
  config:
    active:
      on-profile: local
#  redis:
#    host: localhost
#    port: 6379
  datasource :
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/ordersystem
    username : root
    password : 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
logging:
  level:
    root: info

jwt:
  expiration: 30
  secretKey: my_token_secret

